### PR TITLE
Updates project to Kotlin

### PR DESCRIPTION
**Pull request by jonathan-livly**
Converted CircularSeekbar to Kotlin
Updated the target SDK version to 31
Updated the project's Gradle
Updated the project to Java 11
Removed getter and setter methods and removed Hungarian notation. Should remain backwards compatible.

### CODE REVIEW

**Comment by jonathan-livly** [comment]
Would like to get this merged in but feel that rewriting the gradle script for the CI for this project is out of scope of my work
https://stackoverflow.com/questions/68820339/unable-to-resolve-class-mavendeployment-after-updating-the-gradle-wrapper

**Comment by tankery** [comment]
Hi, @jonathan-livly , appreciate for your PR. I'd love to see the library been rewritten by Kotlin. But sorry we should make the CI works before merge to ensure the basic quality of this library.

The CI failure looks like a conflict between the maven publish plugin and new gradle version. Would you mind split the PR to smaller ones and fix the CI break? We can at least split it in two:

1. Upgrade gradle wrapper, and fix the CI break with the replacement of maven publish plugin.
2. Add Kotlin support and convert the library to Kotlin.

Let me know if you are comfortable on replace the maven publish plugin, or I could do this before you convert to Kotlin. Thanks.

**Comment by jonathan-livly** [comment]
I think I would be most comfortable with you updating the project to use the new maven plugin then I can pull in those changes and PR the Kotlin conversion. Thanks

**Comment by tankery** [comment]
Hi, @jonathan-livly, Gradle wrapper updated, feel free to rebase and convert it to Kotlin. Thanks.

**Comment by jonathan-livly** [comment]
I kept in the change to update to Java 11, but found the library and sample app worked just fine without it.

**Review by tankery — COMMENTED** [review]
Nice work! Thanks for the convert. Just some nit suggestions. Please checkout

**Comment by jonathan-livly** [comment]
Updated

**Comment by tankery** [comment]
Merged, thanks for the work to migrate it to Kotlin!

**Pull request merged**
